import { MockEmployee } from "../mock-data-interfaces";
import { v4 as uuidv4 } from 'uuid'; // Import uuid

export const generateMockEmployees = (): MockEmployee[] => [
  {
    id: uuidv4(), // Generate UUID
    personalId: "BIO1001",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@acmecorp.co.za",
    jobTitle: "Software Engineer",
    salary: 45000,
    hourlyRate: undefined,
    startDate: "2022-01-15",
    idNumber: "9001015000087",
    phoneNumber: "0821234567",
    emergencyContactName: "Jane Doe",
    emergencyContactNumber: "0729876543",
    emergencyContactAddress: "15 Tech Street, Unit 10, Johannesburg, 2001",
    addressLine1: "15 Tech Street",
    addressLine2: "Unit 10",
    city: "Johannesburg",
    province: "Gauteng",
    postalCode: "2001",
    taxReferenceNumber: "1234567890",
    uifNumber: "1234567/8",
    bankName: "FNB",
    bankAccountHolder: "John Doe",
    ibanNumber: "62000000001",
    routingSwiftCode: "250655",
    bankAccountType: "Cheque",
    dateOfBirth: "1990-05-20",
    gender: "Male",
    department: "IT",
    workLocation: "Head Office",
    dateOfConfirmation: "2022-07-15",
    originCountry: "South Africa",
    employmentType: "Permanent",
    portalAccess: true,
    fathersName: "Richard Doe",
    molId: "MOL-JD-001",
    permanentAddress: "15 Tech Street, Unit 10, Johannesburg, 2001",
    paymentMode: "Bank Transfer",
    payFrequency: "Monthly",
    standardDailyHours: 8,
  },
  {
    id: uuidv4(), // Generate UUID
    personalId: "BIO1002",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@acmecorp.co.za",
    jobTitle: "HR Manager",
    salary: 38000,
    hourlyRate: undefined,
    startDate: "2021-03-01",
    idNumber: "8505055000088",
    phoneNumber: "0712345678",
    emergencyContactName: "John Smith",
    emergencyContactNumber: "0831234567",
    emergencyContactAddress: "22 Oak Avenue, Cape Town, 8001",
    addressLine1: "22 Oak Avenue",
    city: "Cape Town",
    province: "Western Cape",
    postalCode: "8001",
    taxReferenceNumber: "0987654321",
    uifNumber: "8765432/1",
    bankName: "Standard Bank",
    bankAccountHolder: "Jane Smith",
    ibanNumber: "07000000002",
    routingSwiftCode: "051001",
    bankAccountType: "Savings",
    dateOfBirth: "1985-01-05",
    gender: "Female",
    department: "Human Resources",
    workLocation: "Cape Town Branch",
    dateOfConfirmation: "2021-09-01",
    originCountry: "South Africa",
    employmentType: "Permanent",
    portalAccess: true,
    fathersName: "David Smith",
    molId: "MOL-JS-002",
    permanentAddress: "22 Oak Avenue, Cape Town, 8001",
    paymentMode: "Bank Transfer",
    payFrequency: "Monthly",
    standardDailyHours: 8,
  },
  {
    id: uuidv4(), // Generate UUID
    personalId: "BIO1003",
    firstName: "Peter",
    lastName: "Jones",
    email: "peter.jones@acmecorp.co.za",
    jobTitle: "Accountant",
    salary: 32000,
    hourlyRate: undefined,
    startDate: "2023-07-20",
    idNumber: "9203035000089",
    phoneNumber: "0601112233",
    emergencyContactName: "Mary Jones",
    emergencyContactNumber: "0769998877",
    emergencyContactAddress: "789 Finance Street, Durban, 4001",
    addressLine1: "789 Finance Street",
    city: "Durban",
    province: "KwaZulu-Natal",
    postalCode: "4001",
    taxReferenceNumber: "1122334455",
    uifNumber: "1122334/4",
    bankName: "Absa",
    bankAccountHolder: "Peter Jones",
    ibanNumber: "90000000003",
    routingSwiftCode: "632005",
    bankAccountType: "Cheque",
    dateOfBirth: "1992-03-10",
    gender: "Male",
    department: "Finance",
    workLocation: "Durban Office",
    dateOfConfirmation: "2024-01-20",
    originCountry: "South Africa",
    employmentType: "Permanent",
    portalAccess: true,
    fathersName: "Robert Jones",
    molId: "MOL-PJ-003",
    permanentAddress: "789 Finance Street, Durban, 4001",
    paymentMode: "Bank Transfer",
    payFrequency: "Monthly",
    standardDailyHours: 8,
  },
  {
    id: uuidv4(), // Generate UUID
    personalId: "BIO1004",
    firstName: "Sarah",
    lastName: "Brown",
    email: "sarah.brown@acmecorp.co.za",
    jobTitle: "Marketing Specialist",
    salary: undefined,
    hourlyRate: 150,
    startDate: "2022-11-10",
    idNumber: "9507075000090",
    phoneNumber: "0845556677",
    emergencyContactName: "David Brown",
    emergencyContactNumber: "0612223344",
    emergencyContactAddress: "321 Creative Lane, Pretoria, 0001",
    addressLine1: "321 Creative Lane",
    city: "Pretoria",
    province: "Gauteng",
    postalCode: "0001",
    taxReferenceNumber: "2233445566",
    uifNumber: "2233445/5",
    bankName: "Nedbank",
    bankAccountHolder: "Sarah Brown",
    ibanNumber: "10000000004",
    routingSwiftCode: "198765",
    bankAccountType: "Savings",
    dateOfBirth: "1995-07-15",
    gender: "Female",
    department: "Marketing",
    workLocation: "Head Office",
    dateOfConfirmation: "2023-05-10",
    originCountry: "South Africa",
    employmentType: "Contract",
    portalAccess: true,
    fathersName: "Michael Brown",
    molId: "MOL-SB-004",
    permanentAddress: "321 Creative Lane, Pretoria, 0001",
    paymentMode: "Bank Transfer",
    payFrequency: "Weekly",
    standardDailyHours: 8,
  },
  {
    id: uuidv4(), // Generate UUID
    personalId: "BIO1005",
    firstName: "David",
    lastName: "Green",
    email: "david.green@acmecorp.co.za",
    jobTitle: "Operations Manager",
    salary: 40000,
    hourlyRate: undefined,
    startDate: "2021-05-01",
    idNumber: "8802025000091",
    phoneNumber: "0798889900",
    emergencyContactName: "Emily Green",
    emergencyContactNumber: "0827776655",
    emergencyContactAddress: "65 Industrial Park, Port Elizabeth, 6001",
    addressLine1: "65 Industrial Park",
    city: "Port Elizabeth",
    province: "Eastern Cape",
    postalCode: "6001",
    taxReferenceNumber: "3344556677",
    uifNumber: "3344556/6",
    bankName: "Capitec",
    bankAccountHolder: "David Green",
    ibanNumber: "45000000005",
    routingSwiftCode: "470010",
    bankAccountType: "Cheque",
    dateOfBirth: "1988-02-28",
    gender: "Male",
    department: "Operations",
    workLocation: "Port Elizabeth Plant",
    dateOfConfirmation: "2021-11-01",
    originCountry: "South Africa",
    employmentType: "Permanent",
    portalAccess: true,
    fathersName: "Paul Green",
    molId: "MOL-DG-005",
    permanentAddress: "65 Industrial Park, Port Elizabeth, 6001",
    paymentMode: "Bank Transfer",
    payFrequency: "Monthly",
    standardDailyHours: 8,
  },
  {
    id: uuidv4(), // Generate UUID
    personalId: "BIO1006",
    firstName: "Emily",
    lastName: "White",
    email: "emily.white@acmecorp.co.za",
    jobTitle: "Customer Support",
    salary: undefined,
    hourlyRate: 120,
    startDate: "2023-02-28",
    idNumber: "9810105000092",
    phoneNumber: "0671112233",
    emergencyContactName: "Michael White",
    emergencyContactNumber: "0743334455",
    emergencyContactAddress: "101 Help Desk Road, Bloemfontein, 9301",
    addressLine1: "101 Help Desk Road",
    city: "Bloemfontein",
    province: "Free State",
    postalCode: "9301",
    taxReferenceNumber: "4455667788",
    uifNumber: "4455667/7",
    bankName: "FNB",
    bankAccountHolder: "Emily White",
    ibanNumber: "62000000006",
    routingSwiftCode: "250655",
    bankAccountType: "Savings",
    dateOfBirth: "1998-10-10",
    gender: "Female",
    department: "Customer Service",
    workLocation: "Bloemfontein Call Center",
    dateOfConfirmation: "2023-08-28",
    originCountry: "South Africa",
    employmentType: "Temporary",
    portalAccess: true,
    fathersName: "James White",
    molId: "MOL-EW-006",
    permanentAddress: "101 Help Desk Road, Bloemfontein, 9301",
    paymentMode: "Bank Transfer",
    payFrequency: "Bi-Weekly",
    standardDailyHours: 8,
  },
  {
    id: uuidv4(), // Generate UUID
    personalId: "BIO1007",
    firstName: "Chris",
    lastName: "Taylor",
    email: "chris.taylor@acmecorp.co.za",
    jobTitle: "Warehouse Assistant",
    salary: undefined,
    hourlyRate: 95,
    startDate: "2024-06-01",
    idNumber: "9901015000093",
    phoneNumber: "0651234567",
    emergencyContactName: "Sarah Taylor",
    emergencyContactNumber: "0739876543",
    emergencyContactAddress: "50 Storage Lane, Johannesburg, 2000",
    addressLine1: "50 Storage Lane",
    city: "Johannesburg",
    province: "Gauteng",
    postalCode: "2000",
    taxReferenceNumber: "5566778899",
    uifNumber: "5566778/8",
    bankName: "Capitec",
    bankAccountHolder: "Chris Taylor",
    ibanNumber: "45000000007",
    routingSwiftCode: "470010",
    bankAccountType: "Savings",
    dateOfBirth: "1999-01-01",
    gender: "Male",
    department: "Operations",
    workLocation: "Warehouse",
    dateOfConfirmation: undefined,
    originCountry: "South Africa",
    employmentType: "Temporary",
    portalAccess: false,
    fathersName: "Mark Taylor",
    molId: "MOL-CT-007",
    permanentAddress: "50 Storage Lane, Johannesburg, 2000",
    paymentMode: "Bank Transfer",
    payFrequency: "Weekly",
    standardDailyHours: 8,
  },
  {
    id: uuidv4(), // Generate UUID
    personalId: "BIO1008",
    firstName: "Anna",
    lastName: "Miller",
    email: "anna.miller@acmecorp.co.za",
    jobTitle: "Part-time Admin",
    salary: undefined,
    hourlyRate: 110,
    startDate: "2024-07-10",
    idNumber: "0002025000094",
    phoneNumber: "0762345678",
    emergencyContactName: "Paul Miller",
    emergencyContactNumber: "0811234567",
    emergencyContactAddress: "12 Admin Street, Cape Town, 8001",
    addressLine1: "12 Admin Street",
    city: "Cape Town",
    province: "Western Cape",
    postalCode: "8001",
    taxReferenceNumber: "6677889900",
    uifNumber: "6677889/9",
    bankName: "Standard Bank",
    bankAccountHolder: "Anna Miller",
    ibanNumber: "07000000008",
    routingSwiftCode: "051001",
    bankAccountType: "Cheque",
    dateOfBirth: "2000-02-02",
    gender: "Female",
    department: "Administration",
    workLocation: "Cape Town Branch",
    dateOfConfirmation: undefined,
    originCountry: "South Africa",
    employmentType: "Temporary",
    portalAccess: false,
    fathersName: "George Miller",
    molId: "MOL-AM-008",
    permanentAddress: "12 Admin Street, Cape Town, 8001",
    paymentMode: "Bank Transfer",
    payFrequency: "Weekly",
    standardDailyHours: 6,
  },
];